#!/bin/bash

echo "=== RealtimeSTT Android APK Builder ==="
echo ""
echo "ERROR: Java 11+ is required but Java 8 is installed."
echo ""
echo "To build this Android app, you need to:"
echo ""
echo "1. Install Java 11 or newer:"
echo "   sudo dnf install java-11-openjdk-devel"
echo ""
echo "2. Switch to Java 11:"
echo "   sudo alternatives --config java"
echo "   (Select Java 11 from the list)"
echo ""
echo "3. Then run:"
echo "   ./gradlew assembleDebug"
echo ""
echo "Alternative: Use Android Studio on a machine with Java 11+"
echo "to build the APK and transfer it to this machine."